In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [6]:
## load the trained model, scaler pickle file and the one hot encoded 
model=load_model('model.h5')

## load the encoders and scalar
with open('onehot_encoder_geo.pkl', 'rb') as file:
    onehot_encoder_geo = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [7]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',  
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [19]:
geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
one_hot_encoded_geo_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
one_hot_encoded_geo_df

/Users/dhruvikaahuja/miniconda3/envs/ann311/lib/python3.11/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [21]:
input_df = pd.DataFrame([input_data])
input_df

   CreditScore Geography  ...  IsActiveMember  EstimatedSalary
0          600    France  ...               1            50000

[1 rows x 10 columns]

In [23]:
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

   CreditScore Geography  ...  IsActiveMember  EstimatedSalary
0          600    France  ...               1            50000

[1 rows x 10 columns]

In [24]:
input_df = pd.concat([input_df.drop('Geography', axis=1), one_hot_encoded_geo_df], axis=1)
input_df

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          600       1  ...                0.0              0.0

[1 rows x 12 columns]

In [26]:
#scaling the input data
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.5744806 ,  1.05131497, -0.45807877, -0.82836952, -1.23566245,
         1.05131497,  0.57735027,  1.        , -0.60880062,  1.29099445,
        -0.61588176, -0.73379939]])

In [27]:
## Predict churn
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step

array([[0.45680138]], dtype=float32)

In [ ]:
prediction_proba = prediction[0][0]
prediction_proba

In [30]:
if prediction_proba > 0.5:
    print('The customer is likey to churn')
else:
    print('The customer is not likely to churn')

NameError: name 'prediction_proba' is not defined